---
- hosts: flaskapp_nodes
  become: yes
  vars:
    - APP_NAME: flaskapp
    - REPOSITORY_URL: https://github.com/jkanclerz/example-flask-app-1.git
  tasks:
    - name: "install os packages"
      yum:
        name: python3, python3-pip, git
    - name: "sync repo"
      git:
        repo: "{{REPOSITORY_URL}}"
        dest: "/opt/{{APP_NAME}}"
    - name: "create user"
      user:
        name: "{{APP_NAME}}"
    - name: "create venv"
      pip:
        requirements: "/opt/{{APP_NAME}}/requirements.txt"
        virtualenv: "/opt/{{APP_NAME}/.venv"
        virtualenv_python: "python3"
    - name: "put systemd cfg"
      template:
        src: files/flaskapp.service
        dest: "/etc/systemd/system/{{APP_NAME}}.service"
    - name: "start service"
      systemd:
        name: "{{APP_NAME}}"
        state: restarted
        daemon_reload: yes
